### PR TITLE
Added Team Deletion

### PR DESCRIPTION
**Pull request by kbristow**
Added delete endpoint to TeamController for team deletion functionality.
Tried to do some cleanup at the same time but it got out of hand. Stopped with the cleanup where I am for now.

### CODE REVIEW

**Comment by Buzzglo** [comment]
Looks like a true delete? Do we do that?

**Comment by kbristow** [comment]
We initially said no for teams. But with the way we create so many test/demo teams it is becoming necessary. We already do true deletes on projects and applications so this just extends that. I do think that disabling teams should still be the actual 'delete' we expose to users, but this is useful for our internal cleanup.

**Comment by Buzzglo** [comment]
Okay so the intention is that this will be end point for us to remove teams?

IDK still feel like we should have a state on a team and change it inactive... if the other guys are cool with this i'm good with code from what I have seen.

**Comment by kbristow** [comment]
I tend to agree, but it is a way bigger change. This would probably be a temporary solution until we have the time for the bigger change. Lets discuss on Tuesday though.

**Pull request merged**
